# Generated by Django 5.1.1 on 2024-11-07 06:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("medicalrecords", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="appointment",
            old_name="doctor",
            new_name="physician",
        ),
        migrations.RenameField(
            model_name="prescription",
            old_name="doctor",
            new_name="physician",
        ),
    ]
