# Generated by Django 5.1.1 on 2024-11-13 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalrecords', '0004_discount_appointment_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='consultation_fee',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
