# Generated by Django 5.1.4 on 2025-12-26 18:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("medicalrecords", "0006_discount_created_at_discount_updated_at"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Appointment",
        ),
    ]
