# Generated by Django 5.1.1 on 2024-11-07 06:24

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        ("medicalrecords", "0002_rename_doctor_appointment_physician_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Nurse",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Nurse",
                "verbose_name_plural": "Nurses",
            },
            bases=("accounts.user",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Receptionist",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Receptionist",
                "verbose_name_plural": "Receptionists",
            },
            bases=("accounts.user",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RenameModel(
            old_name="Operator",
            new_name="Accountant",
        ),
        migrations.RenameModel(
            old_name="Admin",
            new_name="Administrator",
        ),
        migrations.RenameModel(
            old_name="Doctor",
            new_name="Physician",
        ),
        migrations.AlterModelOptions(
            name="accountant",
            options={
                "verbose_name": "Accountant",
                "verbose_name_plural": "Accountants",
            },
        ),
        migrations.AlterModelOptions(
            name="administrator",
            options={
                "verbose_name": "Administrator",
                "verbose_name_plural": "Administrators",
            },
        ),
    ]
