# Generated by Django 6.0.3 on 2026-06-21 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('physician', 'Physician'), ('nurse', 'Nurse'), ('receptionist', 'Receptionist'), ('accountant', 'Accountant'), ('patient', 'Patient')], default='patient', max_length=20),
        ),
    ]
