# Generated by Django 6.0.3 on 2026-07-29 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('physician', 'Physician'), ('nurse', 'Nurse'), ('receptionist', 'Receptionist')], default='receptionist', max_length=20),
        ),
    ]
