# Generated by Django 5.1.1 on 2024-11-07 06:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_nurse_receptionist_rename_operator_accountant_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="physician",
            options={"verbose_name": "Physician", "verbose_name_plural": "Physicians"},
        ),
    ]
