# Generated by Django 5.1.1 on 2024-10-13 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_delete_patient_remove_admin_admin_level_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone_number_country_code',
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
