# Generated by Django 5.1.1 on 2024-10-13 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_phone_number_country_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operator',
            name='department',
        ),
    ]
