# Generated by Django 5.1.1 on 2024-11-10 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_physician_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("age", models.PositiveIntegerField(null=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "height_in_centimeter",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                (
                    "weight_in_kg",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                ("temperature", models.FloatField(blank=True, null=True)),
                (
                    "temperature_method",
                    models.CharField(blank=True, max_length=1, null=True),
                ),
                ("pulse", models.PositiveIntegerField(blank=True, null=True)),
                ("bmi", models.FloatField(blank=True, null=True)),
                ("bmi_status", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "blood_type",
                    models.CharField(
                        choices=[
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("O+", "O+"),
                            ("O-", "O-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                        ],
                        max_length=3,
                        null=True,
                    ),
                ),
                ("blood_pressure_systolic", models.IntegerField(null=True)),
                ("blood_pressure_diastolic", models.IntegerField(null=True)),
                ("allergies", models.TextField(blank=True, max_length=255, null=True)),
                ("emergency_contact_name", models.CharField(max_length=100, null=True)),
                (
                    "emergency_contact_number",
                    models.CharField(max_length=15, null=True),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "patient",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_details",
                        to="accounts.patient",
                    ),
                ),
            ],
        ),
    ]
