# Generated by Django 5.1.1 on 2024-11-12 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_patientdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='physician',
            name='fee_per_consultation',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
