# Generated by Django 5.1.1 on 2024-11-12 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_physician_fee_per_consultation'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdetail',
            name='vip_status',
            field=models.BooleanField(default=False),
        ),
    ]
