# Generated by Django 5.1.1 on 2024-11-13 11:13

import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_patientdetail_vip_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicianAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_days', multiselectfield.db.fields.MultiSelectField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=56)),
                ('work_time_start', models.TimeField(blank=True, null=True)),
                ('work_time_end', models.TimeField(blank=True, null=True)),
                ('lunch_start', models.TimeField(blank=True, null=True)),
                ('lunch_end', models.TimeField(blank=True, null=True)),
                ('physician', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.physician')),
            ],
        ),
    ]
