# Generated by Django 5.1.1 on 2024-11-14 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_physicianavailability'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weekday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=9, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='physicianavailability',
            name='physician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='accounts.physician'),
        ),
        migrations.RemoveField(
            model_name='physicianavailability',
            name='work_days',
        ),
        migrations.AlterField(
            model_name='physicianavailability',
            name='work_time_end',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='physicianavailability',
            name='work_time_start',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='physicianavailability',
            name='work_days',
            field=models.ManyToManyField(to='accounts.weekday'),
        ),
    ]
