# Generated by Django 5.1.1 on 2024-11-15 04:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_weekday_alter_physicianavailability_physician_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="is_vip",
            field=models.BooleanField(default=False),
        ),
    ]
