# Generated by Django 5.1.1 on 2024-11-17 05:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_patient_is_vip"),
    ]

    operations = [
        migrations.RenameField(
            model_name="patientdetail",
            old_name="vip_status",
            new_name="is_vip",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="is_vip",
        ),
    ]
