# Generated by Django 6.0.3 on 2026-03-14 10:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0010_rename_vip_status_patientdetail_is_vip_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PhysicianAvailability",
        ),
        migrations.DeleteModel(
            name="Weekday",
        ),
    ]
