# Generated by Django 5.1.1 on 2024-11-16 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('contact_number', models.PositiveBigIntegerField(blank=True, null=True)),
                ('gst_number', models.CharField(max_length=100)),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('logo', models.ImageField(default='media/default_clinic_logo.webp', upload_to='clinic_logo')),
                ('consultation_duration', models.PositiveIntegerField(null=True)),
            ],
        ),
    ]
