# Generated by Django 6.0.3 on 2026-07-27 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='consultation_duration',
            field=models.PositiveIntegerField(help_text='Duration in minutes', null=True),
        ),
    ]
