# Generated by Django 5.1.1 on 2024-11-07 06:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="routeofadministration",
            name="route_of_administration",
        ),
    ]
