# Generated by Django 5.1.1 on 2024-10-29 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_prescription_diagnosis_prescription_follow_up_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='diagnosis',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='prescription_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
