# Generated by Django 6.0.3 on 2026-03-14 13:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0002_remove_routeofadministration_route_of_administration"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicine",
            name="suppliers",
            field=models.ManyToManyField(
                through="inventory.MedicineSupplier", to="inventory.supplier"
            ),
        ),
    ]
