# Generated by Django 5.1.1 on 2024-10-29 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_prescription_diagnosis_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescriptionmedicine',
            name='prescription',
        ),
        migrations.RemoveField(
            model_name='prescriptionmedicine',
            name='medicine',
        ),
        migrations.DeleteModel(
            name='Prescription',
        ),
        migrations.DeleteModel(
            name='PrescriptionMedicine',
        ),
    ]
