# Generated by Django 6.0.3 on 2026-05-28 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicalrecords', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Weekday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=9, unique=True)),
            ],
            options={
                'verbose_name': 'Weekday',
                'verbose_name_plural': 'Weekdays',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('time', models.TimeField(null=True)),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Pending', 'Pending'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consultation_fee', models.PositiveIntegerField(blank=True, null=True)),
                ('discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medicalrecords.discount')),
                ('patient', models.OneToOneField(limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='patient_appointments', to=settings.AUTH_USER_MODEL)),
                ('physician', models.OneToOneField(limit_choices_to={'role': 'physician'}, on_delete=django.db.models.deletion.CASCADE, related_name='physician_appointments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
                'ordering': ['date', 'time'],
            },
        ),
        migrations.CreateModel(
            name='PhysicianAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_time_start', models.TimeField(null=True)),
                ('work_time_end', models.TimeField(null=True)),
                ('lunch_start', models.TimeField(blank=True, null=True)),
                ('lunch_end', models.TimeField(blank=True, null=True)),
                ('physician', models.OneToOneField(limit_choices_to={'role': 'physician'}, on_delete=django.db.models.deletion.CASCADE, related_name='physician_availability', to=settings.AUTH_USER_MODEL)),
                ('work_days', models.ManyToManyField(to='appointments.weekday')),
            ],
            options={
                'verbose_name': 'Physician Availability',
                'verbose_name_plural': 'Physician Availabilities',
            },
        ),
    ]
