# Generated by Django 6.0.3 on 2026-03-14 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0011_delete_physicianavailability_delete_weekday"),
        ("appointments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Weekday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("Monday", "Monday"),
                            ("Tuesday", "Tuesday"),
                            ("Wednesday", "Wednesday"),
                            ("Thursday", "Thursday"),
                            ("Friday", "Friday"),
                            ("Saturday", "Saturday"),
                            ("Sunday", "Sunday"),
                        ],
                        max_length=9,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PhysicianAvailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("work_time_start", models.TimeField(null=True)),
                ("work_time_end", models.TimeField(null=True)),
                ("lunch_start", models.TimeField(blank=True, null=True)),
                ("lunch_end", models.TimeField(blank=True, null=True)),
                (
                    "physician",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availabilities",
                        to="accounts.physician",
                    ),
                ),
                ("work_days", models.ManyToManyField(to="appointments.weekday")),
            ],
        ),
    ]
