# Generated by Django 6.0.3 on 2026-09-21 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def snapshot_duration(apps, schema_editor):
    Clinic = apps.get_model('clinic', 'Clinic')
    Appointment = apps.get_model('appointments', 'Appointment')
    database = schema_editor.connection.alias
    duration = Clinic.objects.using(database).values_list('consultation_duration', flat=True).first()
    if duration and duration <= 1440:
        Appointment.objects.using(database).update(duration_minutes=duration)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
        ('appointments', '0003_alter_appointment_patient'),
        ('clinic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='duration_minutes',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_appointments', to='accounts.patient'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='physician',
            field=models.ForeignKey(limit_choices_to={'role': 'physician'}, on_delete=django.db.models.deletion.CASCADE, related_name='physician_appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(snapshot_duration, migrations.RunPython.noop),
    ]
