# Generated by Django 5.1.1 on 2024-11-10 08:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patientdetail",
            name="condition",
        ),
        migrations.AddField(
            model_name="patientdetail",
            name="blood_pressure_diastolic",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="patientdetail",
            name="blood_pressure_systolic",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="patientdetail",
            name="bmi",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patientdetail",
            name="bmi_status",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="patientdetail",
            name="height_in_centimeter",
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name="patientdetail",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="patientdetail",
            name="pulse",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patientdetail",
            name="temperature",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patientdetail",
            name="temperature_method",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="patientdetail",
            name="weight_in_kg",
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
