# Generated by Django 5.1.1 on 2024-11-17 07:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounting", "0002_accountspayable_accountsreceivable_asset_invoice"),
    ]

    operations = [
        migrations.RenameField(
            model_name="account",
            old_name="account_type",
            new_name="type",
        ),
    ]
